# .github/workflows/deploy.yml
name: GitHub Pages

on:
  push:
    branches:
      - main  # change to 'master' if needed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/deploy-pages@v4
