name: GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if that's your branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ✅ Upload site content as 'github-pages' artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # folder to publish (includes index.html)

      # ✅ Configure GitHub Pages
      - uses: actions/configure-pages@v4

      # ✅ Deploy to GitHub Pages
      - uses: actions/deploy-pages@v4
